### ISSUE TITLE
Select which inputs are affected by ot.freezeInputs()

### ISSUE THREAD

**Issue by oTree-org** [qwiglydee/otree-front#56]
There are certain inputs that don't need to be frozen.

For example, in an experiment where the user starts each trial by clicking a "continue" button manually. This button actually should be enabled when all the trial inputs are frozen. So freezeInputs() should not affect that button. And if the "continue" button is frozen and you do `resetInputs()`, then you reset all the other inputs.

This could be addressed in one of the following ways:
- Passing an arg like `ot.freezeInputs('my_input')`, `ot.unfreezeInputs('my_input')`
- An attribute `ot-freeze` or `ot-nofreeze` to opt in/out of freezing.

I think some inputs don't need to be frozen ever, such as a 'continue' button that is hidden whenever it is not clickable.

**Comment by qwiglydee** [comment]
Toggling inputs is a matter of `ot-enabled="condition"` directive. This makes it more explicit about which inputs should work in what stages.
The freezing is only for temporary disabling them to prevent preliminary or extra inputs while page is processing.

Also, 'continue' buttons are subject `ot-event` since it doesn't generate input values. The `ot-event` is not a subject of freezing and should be explicitly `ot-enabled`. See examples for 'radio' and 'checkboxes'
