### ISSUE TITLE
Rename ot.nextIteration() to ot.iterateNext()

### ISSUE THREAD

**Issue by oTree-org** [qwiglydee/otree-front#95]
To match the verb-noun naming convention.

**Comment by qwiglydee** [comment]
I now added another handler `ot.completeIteration`
That makes more sense to put test for competion, because it results to completePage, 
also, there're delays for feedback and fade-out animation that is also seem more appropriate into the ending iteration hook.

Together, `onNextIteration` and `onCompleteIteration` rhymes, and similar to `onStartPage/onCompletePage` and `onStartTrial/onCompleteTrial`

**Comment by qwiglydee** [comment]
Replacing with #109
